name: Backend Build Pipeline

on:
  pull_request:
    branches:
      - main # Run this workflow when a PR targets the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23' # Change to match your project's Java version
        distribution: 'temurin'

    - name: Navigate to Backend Directory and List Files (Optional)
      run: ls
      working-directory: backend # Verify the backend directory structure

    - name: Grant Execute Permissions for Gradle Wrapper
      run: chmod +x gradlew
      working-directory: backend

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: backend
