name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.9'
        
    - name: Step into backend directory
      run: cd backend
      working-directory: backend # Ensure this command runs in the backend directory
    
    - name: Grant Gradle Permissions
      run: chmod +x gradlew
      working-directory: backend # Ensure this command runs in the backend directory

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      working-directory: backend # Ensure this command runs in the backend directory

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Generate and Submit Dependency Graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      working-directory: backend # Ensure this command runs in the backend directory
